// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFtaXettw1c1fYsAiVS7Vsv5EUCpzx0Lg',
    appId: '1:717225300393:web:db856227a1e1c2f7caf4b8',
    messagingSenderId: '717225300393',
    projectId: 'corre-aqui-app',
    authDomain: 'corre-aqui-app.firebaseapp.com',
    storageBucket: 'corre-aqui-app.firebasestorage.app',
    measurementId: 'G-SSB2H48PGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtLfMquqx2bkIiLI0DjRo1mXqv_Kzvf8M',
    appId: '1:717225300393:android:4cbd9a879ee0714dcaf4b8',
    messagingSenderId: '717225300393',
    projectId: 'corre-aqui-app',
    storageBucket: 'corre-aqui-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpmWCzEHGlOA0_U8I5dUbugdCnCucNdB0',
    appId: '1:717225300393:ios:7665e8cae2468842caf4b8',
    messagingSenderId: '717225300393',
    projectId: 'corre-aqui-app',
    storageBucket: 'corre-aqui-app.firebasestorage.app',
    iosBundleId: 'com.example.correAquiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpmWCzEHGlOA0_U8I5dUbugdCnCucNdB0',
    appId: '1:717225300393:ios:7665e8cae2468842caf4b8',
    messagingSenderId: '717225300393',
    projectId: 'corre-aqui-app',
    storageBucket: 'corre-aqui-app.firebasestorage.app',
    iosBundleId: 'com.example.correAquiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFtaXettw1c1fYsAiVS7Vsv5EUCpzx0Lg',
    appId: '1:717225300393:web:1b716e40db8d716ccaf4b8',
    messagingSenderId: '717225300393',
    projectId: 'corre-aqui-app',
    authDomain: 'corre-aqui-app.firebaseapp.com',
    storageBucket: 'corre-aqui-app.firebasestorage.app',
    measurementId: 'G-FV56E38P6L',
  );
}
